temp <- read.delim("household_power_consumption.txt",sep=";",header=T)
data <- subset(temp,Date=="1/2/2007" | Date == "2/2/2007")
date_time = strptime(paste(data$Date,data$Time),format="%d/%m/%Y %H:%M:%S")
png("plot3.png",width=480,height=480)
plot(date_time,data$Sub_metering_1,type="l",ylab="Energy sub metering",xlab=NA)
lines(date_time,data$Sub_metering_2,type="l",col="red")
lines(date_time,data$Sub_metering_3,type="l",col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1)
dev.off()

