temp <- read.delim("household_power_consumption.txt",sep=";",header=T)
temp$Date = as.Date(temp$Date,format="%d/%m/%Y")
data <- subset(temp,Date=="2007-02-01" | Date == "2007-02-02")
png("plot1.png",width=480,height=480)
hist(as.numeric(data$Global_active_power), col="red",main="Global Active Power",xlab="Global Active Power (kilowatts)")
dev.off()
